config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'
  resources :users
  resources :posts do
    resources :comments
    resources :favorites, only: [:create, :destroy]
  end
  resources :images, only: [:index]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, :omniauth_providers => [:google_oauth2, :twitter, :facebook]

  has_many :posts, dependent: :delete_all
  has_many :comments, dependent: :delete_all
  has_many :favorites, dependent: :delete_all
  has_many :favorited_posts, through: :favorites, source: :post

  def already_favorited?(post)
    self.favorites.exists?(post_id: post.id)
  end

  def self.find_for_google_oauth2(auth)
    user = User.where(email: auth.info.email).first
    unless user
      user = User.create(name:     auth.info.name,
                         provider: auth.provider,
                         uid:      auth.uid,
                         email:    auth.info.email,
                         token:    auth.credentials.token,
                         password: Devise.friendly_token[0, 20])
    end
    user
  end

  def self.find_for_facebook(auth)
    user = User.where(email: auth.info.email).first
    unless user
      user = User.create(name:     auth.info.name,
                         provider: auth.provider,
                         uid:      auth.uid,
                         email:    auth.info.email,
                         token:    auth.credentials.token,
                         password: Devise.friendly_token[0, 20])
    end
    user
  end

  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first

    unless user
      user = User.create(
        uid:      auth.uid,
        provider: auth.provider,
        email:    User.dummy_email(auth),
        password: Devise.friendly_token[0, 20],
        name: auth.info.name
      )
    end

    user
  end

  private

  def self.dummy_email(auth)
    "#{auth.uid}-#{auth.provider}@example.com"
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order("id desc")
    @favorite = Favorite.find_by(user_id: current_user.id)
  end

  def edit
    @user = current_user
  end

  def update
    user = User.find(params[:id])
    user.update(user_params) if user.id == current_user.id
    if user.save
      redirect_to controller: :posts, action: :index
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="user-edit">

  <div class="row">
    <div class="col l4"></div>
    <div class="col l4">
      <h4 class="user-edit__title"><i class="fas fa-user-edit"></i>&emsp;ユーザー情報編集</h4>
      <%= form_for @user, method: :patch do |f| %>
      <div class="row">
        <div class="input-field col l12">
          <div id="first_name" type="text" class="validate"><%= f.text_field :name %></div>
          <label class="active" for="first_name2">Name</label>
        </div>
      </div>


      <div class="row">
        <div class="input-field col s12">
          <div id="email" type="email" class="validate"><%= f.text_field :email %></div>
          <label class="active" for="first_name2">Email</label>
        </div>
      </div>
      <button class="col l6 btn waves-effect waves-light  grey darken-1 user-edit__btn" type="submit" name="action">
      <%= f.submit "" %>編集する
      <i class="material-icons right">build</i>
      </button>
    </div>
    <div class="col l4"></div>
  </div>


  <% end %>
</div>

app/views/users/show.html.erb
<div class="post-index-main-back">

  <div class="post-index-grid">

    <% if @user == current_user %>
      <div class="post-index-main-back__title">あなたの投稿</div>
    <% else %>
      <div class="post-index-main-back__title"><%= @user.name %>さんの投稿</div>
    <% end %>

    <% @posts.each do |post| %>
    <div class="post-index-main__body uk-card-small uk-card-default">
      <div class="uk-card-body">
        <%= simple_format(post.body, class: "post-index-main__body__comment") %>
      </div>
      <% post.images.each do |image| %>
      <span uk-lightbox>
        <%= link_to("#{image.image_id.url}") do %>
          <%= image_tag "#{image.image_id.url}", width: "150" %>
        <% end %>
      </span>
      <% end %>
      <div class="post-index-main__body__footer uk-card-footer">
        <span class="post-index-main__body__footer__name"><%= post.user.name %></span>
        <span class="post-index-main__body__footer__date"><%= post.created_at.strftime("%Y/%m/%d %H:%M") %></span>
        <%= link_to(post_path(post), style: "text-decoration: none;") do %>
          <span class="post-index-main__body__footer__icon" uk-icon="icon: comment"></span>
        <% end %>
        <span class="post-index-main__body__footer__icon-count"><%= post.comments.count %></span>

        <%= render partial: "posts/posts", locals: {post: post} %>
<!--         <span class="post-index-main__body__footer__icon-heart" uk-icon="icon: heart"></span>
        <span class="post-index-main__body__footer__icon-count">0</span> -->
        <%= link_to "コメントする", post_path(post), class: "post-index-main__body__footer__comment", style: "text-decoration: none;" %>

        <% if post.user.id == current_user.id %>

        <%= link_to "",edit_post_path(post), class: "fas fa-wrench fa-lg post-index-main__body__footer__edit", style: "text-decoration: none;" %>

        <%= link_to "", post_path(post.id), method: :delete, class: "far fa-trash-alt fa-lg post-index-main__body__footer__edit", data: { confirm: '削除しますか？' } %>

        <% else %>
        <% end %>
      </div>
    </div>
    <% end %>

  </div>

  <div class="side-grid">

    <div class="side__body uk-card-small uk-card-default">
      <div class="uk-card-body side__body__box">
        <p class="side__body__comment__next">
          ユーザー名: <%= @user.name %>
        </p>

        <%= link_to edit_user_path(current_user) do %>
        <div class="btn waves-effect waves-light grey darken-1 side__body__box__btn">
          <i class="fas fa-user-edit side__body__box__btn__edit"></i><span>プロフィールを編集</span>
        </div>
        <% end %>

      </div>
    </div>

  </div>

</div>