config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'
  resources :users
  resources :posts do
    resources :comments
    resources :favorites, only: [:create, :destroy]
  end
  resources :images, only: [:index]
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :delete_all
  has_many :images, dependent: :delete_all
  has_many :favorites, dependent: :delete_all
  has_many :favorited_users, through: :favorites, source: :user

  accepts_nested_attributes_for :images
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: :index

  def index
    @user = current_user
    @posts = Post.order("id desc").page(params[:page]).per(20)
    if user_signed_in?
      @favorite = Favorite.find_by(user_id: current_user.id)
    end
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @comments = @post.comments.order("id desc")
    @comment = Comment.new
    if user_signed_in?
      @favorite = Favorite.find_by(user_id: current_user.id)
    end
  end

  def new
    @post = Post.new
    1.times { @post.images.build }
  end

  def create
    post = Post.create(post_params)
    if post.save
      redirect_to controller: :posts, action: :index
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
    0.times { @post.images.build }
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params) if @post.user_id == current_user.id
    if @post.save
      redirect_to controller: :posts, action: :show
    else
      render :edit
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy if post.user_id == current_user.id
    redirect_to controller: :posts, action: :index, alert: '削除しますか？'
  end

  private
  def post_params
    params.require(:post).permit(:body, images_attributes: [:image_id]).merge(user_id: current_user.id)
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_posts.html.erb
<span id="favorite-link-<%= post.id %>">

  <% if user_signed_in? %>
    <% if current_user.already_favorited?(post) %>
      <%= link_to(post_favorite_path(post, @favorite), post: "#{post.id}", class: "heart-icon", method: :delete, style: "text-decoration: none;", remote: true) do %>
        <span class="post-index-main__body__footer__icon-favorited" uk-icon="icon: heart"></span>
      <% end %>
    <% else %>
      <%= link_to(post_favorites_path(post), class: "heart-icon", method: :post, style: "text-decoration: none;", remote: true) do %>
        <span class="post-index-main__body__footer__icon-heart" uk-icon="icon: heart"></span>
      <% end %>
    <% end %>
  <% else %>
    <%= link_to(new_user_session_path, style: "text-decoration: none;") do %>
      <span class="post-index-main__body__footer__icon-heart" uk-icon="icon: heart"></span>
    <% end %>
  <% end %>
  <span class="post-index-main__body__footer__icon-count"><%= post.favorites.count %></span>

</span>

app/views/posts/edit.html.erb
<!-- <div class="post-new">
  <div class="row">
    <div class="col l2"></div>
    <div class="col l8">
      <div class="post-new__title">
        <i class="fas fa-wrench fa-2x post-new__title__icon"></i>
        <span class="post-new__title__text">投稿編集</span>
      </div>
      <%= @post.body %>

    </div>
    <div class="col l2"></div>
  </div>
</div> -->


<div class="post-new">
  <div class="row">
    <div class="col l2"></div>
    <div class="col l8">
      <div class="post-new__title">
        <i class="fas fa-wrench fa-2x post-new__title__icon"></i>
        <span class="post-new__title__text">投稿編集</span>
      </div>
      <%= form_for @post do |f| %>
      <%= f.text_area :body, placeholder: "text", autofocus: true, :size => "20x10", id: "textarea1", class: "grey lighten-5 new_text_field materialize-textarea post-new__textarea" %>
      <%= f.fields_for :images do |image| %>
      <div class="post-new__file-field">
        <div class="post-new__file-field__outputImage">
          <%= image_tag image.object.image_id.url %>





        </div>
        <label class="uk-button uk-button-default">ファイルを選択
        <%= image.file_field :image_id, style: "display:none", class: "inputFile" %>
        </label>
      </div>
      <% end %>
      <button class="btn waves-effect waves-light btn-large post-new__button" type="submit" name="action">
        <%= f.submit "投稿する" %>
        <i class="material-icons right">send</i>
      </button>
      <% end %>
    </div>
    <div class="col l2"></div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="post-index-main">
  <div class="post-index-main__transparent">

  <div class="post-index-grid">

    <% @posts.each do |post| %>
    <div class="post-index-main__body uk-card-small uk-card-default">
      <div class="uk-card-body">
        <%= simple_format(post.body, class: "post-index-main__body__comment") %>
      </div>
      <% post.images.each do |image| %>
      <span uk-lightbox>
        <%= link_to("#{image.image_id}") do %>
          <%= image_tag "#{image.image_id}", width: "150" %>
        <% end %>
      </span>
      <% end %>
      <div class="post-index-main__body__footer uk-card-footer">
        <%= link_to(user_path(post.user), style: "text-decoration: none;") do %>
        <span class="post-index-main__body__footer__name"><%= post.user.name %></span>
        <span class="post-index-main__body__footer__date"><%= post.created_at.strftime("%Y/%m/%d %H:%M") %></span>
        <% end %>
        <%= link_to(post_path(post), style: "text-decoration: none;") do %>
        <span class="post-index-main__body__footer__icon" uk-icon="icon: comment"></span>
        <% end %>
        <span class="post-index-main__body__footer__icon-count"><%= post.comments.count %></span>

        <!-- いいね機能 -->
          <%= render partial: "posts/posts", locals: {post: post} %>

        <%= link_to "コメントする", post_path(post), class: "post-index-main__body__footer__icon", style: "text-decoration: none;" %>
      </div>
    </div>
    <% end %>

      <%= paginate @posts %>


  </div>

  <div class="side-grid">

    <div class="side__body uk-card-small uk-card-default">
      <div class="uk-card-body">
        <p class="side__body__comment__next">NEXT MATCH</p>
        <p class="side__body__comment__team">vs 清水エスパルス</p>
        <p class="side__body__comment__date">9月29日（日） 19:00〜</p>
        <p class="side__body__comment__place">@ BMWスタジアム</p>
      </div>
    </div>

  </div>

  </div>

</div>

app/views/posts/new.html.erb
<div class="post-new">
  <div class="row">
    <div class="col l2"></div>
    <div class="col l8">
      <div class="post-new__title">
        <i class="far fa-envelope fa-2x post-new__title__icon"></i>
        <span class="post-new__title__text">新規投稿</span>
      </div>
      <%= form_for @post do |f| %>
      <%= f.text_area :body, placeholder: "text", autofocus: true, :size => "20x10", id: "textarea1", class: "grey lighten-5 new_text_field materialize-textarea post-new__textarea" %>
      <%= f.fields_for :images do |image| %>
      <div class="post-new__file-field">
        <div class="post-new__file-field__outputImage">
          <i class="far fa-image fa-3x post-new__file-field__icon"></i>
        </div>
        <label class="uk-button uk-button-default">ファイルを選択
        <%= image.file_field :image_id, style: "display:none", class: "inputFile" %>
        </label>
      </div>
      <% end %>
      <button class="btn waves-effect waves-light btn-large post-new__button" type="submit" name="action">
        <%= f.submit "投稿する" %>
        <i class="material-icons right">send</i>
      </button>
      <% end %>
    </div>
    <div class="col l2"></div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="post-show-main">

  <div class="post-show-grid">

    <% if @user == current_user %>
      <div class="post-show-main__title">あなたの投稿</div>
    <% else %>
      <div class="post-show-main__title"><%= @user.name %>さんの投稿</div>
    <% end %>

    <div class="post-show-main__body uk-card-small uk-card-default">
      <div class="uk-card-body">
        <%= simple_format((@post.body), class: "post-show-main__body__comment") %>
      </div>
      <% @post.images.each do |image| %>
      <span uk-lightbox>
        <%= link_to("#{image.image_id.url}") do %>
          <%= image_tag "#{image.image_id.url}", width: "150" %>
        <% end %>
      </span>
      <% end %>
      <div class="post-show-main__body__footer uk-card-footer">
        <span class="post-show-main__body__footer__name"><%= @post.user.name %></span>
        <span class="post-show-main__body__footer__date"><%= @post.created_at.strftime("%Y/%m/%d %H:%M") %></span>
        <%= link_to(post_path(@post), style: "text-decoration: none;") do %>
          <span class="post-show-main__body__footer__icon" uk-icon="icon: comment"></span>
        <% end %>
        <span class="post-show-main__body__footer__icon-count"><%= @post.comments.count %></span>

        <%= render partial: "posts/posts", locals: {post: @post} %>
<!--         <span class="post-show-main__body__footer__icon-heart" uk-icon="icon: heart"></span>
        <span class="post-show-main__body__footer__icon-count">0</span> -->
        <%= link_to "コメントする", post_path(@post), class: "post-show-main__body__footer__comment", style: "text-decoration: none;" %>

        <% if @post.user.id == current_user.id %>

        <%= link_to "",edit_post_path(@post), class: "fas fa-wrench fa-lg post-show-main__body__footer__edit", style: "text-decoration: none;" %>

        <%= link_to "", post_path(@post.id), method: :delete, class: "far fa-trash-alt fa-lg post-show-main__body__footer__edit", data: { confirm: '削除しますか？' } %>

        <% else %>
        <% end %>
      </div>
    </div>


<!--     <div class="post-show-main__title">コメント一覧</div>

    <%= form_for [@post, @comment] do |f| %>
    <%= f.text_area :body, placeholder: "コメント入力欄", autocomplete: "off", class: "grey lighten-5 new_text_field materialize-textarea post-show-main__textarea" %>
      <button class="post-show-main__comment-box waves-effect waves-light btn-small" type="submit" name="action">
        <%= f.submit "コメントする" %>
        <i class="material-icons right">comment</i>
      </button>
    <% end %> -->


    <div class="post-show-main__title">コメント一覧</div>

    <%= form_for [@post, @comment] do |f| %>
    <%= f.text_area :body, placeholder: "コメント入力欄", autocomplete: "off", class: "grey lighten-5 new_text_field materialize-textarea post-show-main__textarea" %>
      <button class="post-show-main__comment-box waves-effect waves-light btn-small" type="submit" name="action">
        <%= f.submit "コメントする" %>
        <i class="material-icons right">comment</i>
      </button>
    <% end %>

    <% @comments.each do |f| %>
    <div class="post-show-main__comment uk-card-small uk-card-default">
      <div class="uk-card-body">
        <span class="post-show-main__body__name-date"><%= f.user.name %></span>
        <span class="post-show-main__body__name-date"><%= f.created_at.strftime("%Y/%m/%d %H:%M") %></span>
        <%= simple_format((f.body), class: "post-show-main__body__comment") %>
      </div>
    </div>
    <% end %>

  </div>

  <div class="side-grid">

    <div class="side__body uk-card-small uk-card-default">
      <div class="uk-card-body">
        <p class="side__body__comment__next">NEXT MATCH</p>
        <p class="side__body__comment__team">vs ヴィッセル神戸</p>
        <p class="side__body__comment__date">7月14日（日） 19:00〜</p>
        <p class="side__body__comment__place">@ BMWスタジアム</p>
      </div>
    </div>

  </div>

</div>