config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'
  resources :users
  resources :posts do
    resources :comments
    resources :favorites, only: [:create, :destroy]
  end
  resources :images, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :post

  mount_uploader :image_id, ImageUploader
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :delete_all
  has_many :images, dependent: :delete_all
  has_many :favorites, dependent: :delete_all
  has_many :favorited_users, through: :favorites, source: :user

  accepts_nested_attributes_for :images
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, :omniauth_providers => [:google_oauth2, :twitter, :facebook]

  has_many :posts, dependent: :delete_all
  has_many :comments, dependent: :delete_all
  has_many :favorites, dependent: :delete_all
  has_many :favorited_posts, through: :favorites, source: :post

  def already_favorited?(post)
    self.favorites.exists?(post_id: post.id)
  end

  def self.find_for_google_oauth2(auth)
    user = User.where(email: auth.info.email).first
    unless user
      user = User.create(name:     auth.info.name,
                         provider: auth.provider,
                         uid:      auth.uid,
                         email:    auth.info.email,
                         token:    auth.credentials.token,
                         password: Devise.friendly_token[0, 20])
    end
    user
  end

  def self.find_for_facebook(auth)
    user = User.where(email: auth.info.email).first
    unless user
      user = User.create(name:     auth.info.name,
                         provider: auth.provider,
                         uid:      auth.uid,
                         email:    auth.info.email,
                         token:    auth.credentials.token,
                         password: Devise.friendly_token[0, 20])
    end
    user
  end

  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first

    unless user
      user = User.create(
        uid:      auth.uid,
        provider: auth.provider,
        email:    User.dummy_email(auth),
        password: Devise.friendly_token[0, 20],
        name: auth.info.name
      )
    end

    user
  end

  private

  def self.dummy_email(auth)
    "#{auth.uid}-#{auth.provider}@example.com"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def after_sign_in_path_for(resource)
    root_path
  end

  def after_sign_out_path_for(resource)
    new_user_session_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to controller: :posts, action: :show, id: params[:post_id]
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:body).merge(user_id: current_user.id, post_id: params[:post_id])
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_variables

  def create
    @favorite = Favorite.new(user_id: current_user.id, post_id: params[:post_id])
    @favorite.save
    # redirect_back(fallback_location: root_path)
    # render json: @favorite.id
    # render json: @favorite
  end

  def destroy
    @favorite = Favorite.find_by(user_id: current_user.id, post_id: params[:post_id])
    @favorite.destroy
    # redirect_back(fallback_location: root_path)
    # render json: @favorite.id
    # render json: @favorite
  end

  private

  def set_variables
    @post = Post.find(params[:post_id])
    @id_name = "#favorite-link-#{@post.id}"
  end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  def index
    @images = Image.order("id desc")
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: :index

  def index
    @user = current_user
    @posts = Post.order("id desc").page(params[:page]).per(20)
    if user_signed_in?
      @favorite = Favorite.find_by(user_id: current_user.id)
    end
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @comments = @post.comments.order("id desc")
    @comment = Comment.new
    if user_signed_in?
      @favorite = Favorite.find_by(user_id: current_user.id)
    end
  end

  def new
    @post = Post.new
    1.times { @post.images.build }
  end

  def create
    post = Post.create(post_params)
    if post.save
      redirect_to controller: :posts, action: :index
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
    0.times { @post.images.build }
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params) if @post.user_id == current_user.id
    if @post.save
      redirect_to controller: :posts, action: :show
    else
      render :edit
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy if post.user_id == current_user.id
    redirect_to controller: :posts, action: :index, alert: '削除しますか？'
  end

  private
  def post_params
    params.require(:post).permit(:body, images_attributes: [:image_id]).merge(user_id: current_user.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order("id desc")
    @favorite = Favorite.find_by(user_id: current_user.id)
  end

  def edit
    @user = current_user
  end

  def update
    user = User.find(params[:id])
    user.update(user_params) if user.id == current_user.id
    if user.save
      redirect_to controller: :posts, action: :index
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>bellboard</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.1.6/css/uikit.min.css" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.1.6/js/uikit.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.1.6/js/uikit-icons.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>

<body>
  <header class="header">
    <ul class="header__top">

      <%= link_to(posts_path) do %>
      <li class="header__top__left">BELLBOARD</li>
      <% end %>

      <li class="header__top__list-first"><span uk-icon="icon: menu; ratio: 1.5"></span>
        <ul class="header__top__list__child">
          <% if user_signed_in? %>
          <%= link_to(user_path(current_user)) do %>
          <li class="header__top__list-first__child__item">マイページ</li>
          <% end %>
          <% end %>
          <%= link_to(posts_path) do %>
          <li class="header__top__list-first__child__item">試合結果</li>
          <% end %>
          <li class="header__top__list-first__child__item">試合予定</li>
          <%= link_to(images_path) do %>
          <li class="header__top__list-first__child__item">投稿画像一覧</li>
          <% end %>
          <% if user_signed_in? %>
          <%= link_to(destroy_user_session_path, method: :delete) do %>
          <li class="header__top__list-first__child__item">ログアウト</li>
          <% end %>
          <% end %>
        </ul>
      </li>

      <% if user_signed_in? %>
      <li class="header__top__list-second uk-float-right"><span class="header__top__list-second__icon uk-badge">0</span>
        <span uk-drop="boundary: .header__top__list;delay-show: 500; delay-hide: 200">
          <div class="uk-card-small uk-card-default uk-card-body">未読コメント0件</div>
        </span>
      </li>
      <% else %>
      <%= link_to(new_user_session_path) do %>
      <li class="header__top__list">ログイン</li>
      <% end %>
      <% end %>

      <%= link_to(new_post_path) do %>
      <li class="header__top__list">投稿する</li>
      <% end %>

    </ul>
  </header>
  <%= yield %>

</body>
</html>